Update searchform.js
Symbiota/Symbiota pull request #1336
Opened 2024-05-16 21:41 UTC by GregPost-ASU

Fix sessionStorage.querystring bug.  Javascript was not handling setting db (collections) checkbox array from user sessionStorage.

# Pull Request Checklist:

# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [ ] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [ ] Comment which GitHub issue(s), if any does this PR address
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2024-05-16 21:53 UTC, themerekat approved these changes
Yay, it works!

2024-05-16 23:00 UTC, Atticus29 requested changes
Don't have a ton of time for code work today because today is a hospital day.

But locally, I was able to reproduce the problem. It seems like this fix doesn't fix the problem for me locally (on the CCH2 database), and it also results in the collector's last name field also not persisting. In other words, this code seems to cause a reversion as well...

2024-05-16 23:01 UTC, Atticus29 commented
> Don't have a ton of time for code work today because today is a hospital day.
> 
> But locally, I was able to reproduce the problem. It seems like this fix doesn't fix the problem for me locally (on the CCH2 database), and it also results in the collector's last name field also not persisting. In other words, this code seems to cause a reversion as well...

As a total aside, I could have sworn that I solved this original issue before. 🤔 .

2024-05-16 23:16 UTC, themerekat commented
@Atticus29 now that you mention it...I cannot reproduce Jason's problem in CCH2 in my Firefox browser either. @GregPost-ASU , did you?

2024-05-16 23:17 UTC, themerekat requested changes
See discussion with Mark

2024-05-17 20:40 UTC, GregPost-ASU commented
I was able to reproduce the issue in both Chrome and Firefox on CCH2 and locally.

I think this fixes #1297, #1302, & #1324

2024-05-17 21:03 UTC, themerekat approved these changes

2024-05-17 21:18 UTC, merged

2024-05-17 21:59 UTC, GregPost-ASU commented
Reverted merge due to testing on Dev server still failing.  The issue appears to be that the ID of the collection checkboxes change depending on whether they are grouped by categories or not.