Head template adjustment and base.css into main.css merge
Symbiota/Symbiota pull request #1514
Opened 2024-07-16 11:17 UTC by egbot

- Move majority of php coding out of head_template into symbbase.org. Trying to keep code to a minimum within head import file in order to maintain ability for us to modify code algorithms without having to explicitly change head.php files within each portal install.
- Move css out of head_template.php into separate css file, to again maintain ability to globally modify these styles within future code versions.
- Move header and footer link/import head so that portal administrator can point to different version if they want (e.g. header_button_menu.css)
- Remove css definitions from base.css duplicated within main.css
- Move unique css definitions from base.css into main.css
- Transfer main.css styles that are only used within a single file into target file
- Remove unused or duplicated css from checklist.css
- Remove collectiontable and categorytitle styles, which do not appear to be used anywhere within code

# Pull Request Checklist:
# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [ ] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [ ] Comment which GitHub issue(s), if any does this PR address
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2024-07-16 18:00 UTC, GregoryPost approved these changes
Pulled to local dev and rebuilt includes/head.php, footer.php, and header.php from templates.  Rough review everything looks good.

2024-07-17 23:28 UTC, Atticus29 reviewed
I haven't finished the review, but I just wanted to say that the accessibility mode stuff works if using the button in the footer to toggle, but not if using the user preference.

I tested this in the Development branch as well, and it looks like this reversion pre-dates this current PR. I created a rainy day ticket for it [here](https://github.com/BioKIC/Symbiota/issues/1524), and I don't think that it needs to be done as part of the work herein.

I still want to look at a few more things...

2024-07-18 01:56 UTC, Atticus29 requested changes
I think a few minor things, but makes sense to me.

How concerned are we that there are still two distinct main.css files (css/symb/main.css and css/v202209/symbiota/main.css)? Is that intentional?

2024-07-18 01:56 UTC, Atticus29 commented on config/symbbase.php
> +		$ACCESSIBILITY_ACTIVE == true;
Why `==` here?

2024-07-18 01:56 UTC, Atticus29 commented on config/symbbase.php
> +		$ACCESSIBILITY_ACTIVE == true;
Why `==` here instead of `=`?

2024-07-18 01:56 UTC, Atticus29 commented on imagelib/search.php
> +	<style type="text/css">
The type attribute is obsolete here and gets flagged by total validator pro.

2024-07-18 01:56 UTC, Atticus29 commented on config/symbbase.php
> +		$ACCESSIBILITY_ACTIVE == true;
I'm also confused why both of these seem like they ought to set $ACCESSIBILITY_ACTIVE to true. But it seems to be working as expected when I toggle between modes, so I guess it's ok??

Or perhaps it's the `==` bug that's hiding this second bug?

2024-07-18 02:06 UTC, Atticus29 commented on css/v202209/symbiota/main.css
> +/* Style and Font imports
A blurb at the top of this file to clarify what distinguishes it from css/symb/main.css would be helpful here.

2024-07-22 12:15 UTC, merged