adjusting css on crowdsourceeditor so that fonts rendder correctly
Symbiota/Symbiota pull request #1759
Opened 2024-09-30 19:20 UTC by MuchQuak

# Issue #1753

# Summary
Fixes Styling on Crowdsource page that got disrupted from font-size bump.

# Pull Request Checklist:

# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [ ] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [ ] Comment which GitHub issue(s), if any does this PR address
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2024-09-30 19:26 UTC, themerekat commented
Is there a reason why this form is so scrunched over to the left side of the page? Below is a screenshot of the entire browser window width.
![image](https://github.com/user-attachments/assets/308592e9-2315-4d49-839d-7c605c405308)
With the increase in font, it would be extra nice if it could take up more of the page so that the rows come out cleanly.

2024-09-30 20:15 UTC, themerekat approved these changes

2024-09-30 21:07 UTC, themerekat commented
Well rats, now I see why this styling might be the way it was...when you click on the arrows next to Long Form, it makes a bigger, more detailed form. With the new change, that ends up pushing the image off the page. You'll need to be able to see the image so that you can transcribe the specimen data from it.
![image](https://github.com/user-attachments/assets/9dee2ea2-0ee1-4a0f-aae9-d8e8aa8d068d)

2024-09-30 21:08 UTC, themerekat requested changes
See comment above

2024-09-30 21:25 UTC, themerekat commented on css/symbiota/main.css
>  /* JQUERY UI modifications */
@egbot , I'm having second thoughts about the previous change to .ui-tabs-panel. I think it could go back to 1rem. Apologies for my haste...

2024-09-30 21:35 UTC, themerekat commented on css/symbiota/main.css
>  /* JQUERY UI modifications */
Ok, so should the change back to 1.0 be approved in this particular PR, then?

2024-10-01 04:18 UTC, MuchQuak commented on css/symbiota/main.css
>  /* JQUERY UI modifications */
I could just override only that in file which would let the form look better without disruptive changes.

2024-10-01 04:20 UTC, MuchQuak commented
> Well rats, now I see why this styling might be the way it was...when you click on the arrows next to Long Form, it makes a bigger, more detailed form. With the new change, that ends up pushing the image off the page. You'll need to be able to see the image so that you can transcribe the specimen data from it. ![image](https://private-user-images.githubusercontent.com/16688784/372250997-9dee2ea2-0ee1-4a0f-aae9-d8e8aa8d068d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MzA3NzYsIm5iZiI6MTcyNzczMDQ3NiwicGF0aCI6Ii8xNjY4ODc4NC8zNzIyNTA5OTctOWRlZTJlYTItMGVlMS00YTBmLWFhZTktZDhlOGFhOGQwNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDIxMDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNjQxYjE0N2ExNjRmNDljNzhkNGM0N2ZhOGI0NmE5Y2Y2MWU3ZWE4ZWJlMTIwYWU2OWQxYzZkOWUxMjgxYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JjC7hj4U7jvm_KYMiiaXTAAwOAWbmHMXeE3llXlXr1A)

Is there a need for the long form toggle if the form is responsive to the screen size? I don't see why keeping it would make this form any easier to use with the added toggle?

2024-10-01 17:09 UTC, MuchQuak commented
> Concerning the occurrence editor, I recommend that we simply revert styles back to pre-3.1.1 within the hotfix, and then do style adjustments to the crowdsourcing form within the Development branch, unless there is a significant issue that was introduced in 3.1 rollout. I'm happy to meet to discuss the crowdsourcing tool and possible redesigns. Especially context of the pending SAPLING proposal.

By pre 3.1.1 do you mean just those tab rules with 1rem instead of 1.2rem?

2024-10-01 18:22 UTC, themerekat commented
Clicking "long form" actually makes the form more narrow. Is the styling not uniform between long and short forms?

2024-10-07 21:31 UTC, themerekat approved these changes

2024-10-08 22:01 UTC, merged