Add occurrence identifiers to upload preview
Symbiota/Symbiota pull request #1905
Opened 2024-11-22 00:21 UTC by MuchQuak

# Issue #1878

# Summary
Adds omoccuridentifer values to otherCatalogNumbers in the upload preview to accurately depict what the end state will be.

# Pull Request Checklist:

# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and PR'd using the **merge** option (not squashed) into the `hotfix` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [ ] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [ ] Comment which GitHub issue(s), if any does this PR address
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge into the `hotfix` branch, remember to use the **merge** option (i.e., no squash).
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a merge from the `hotfix` branch into the `master` branch use the **squash & merge** option
  - [ ] a subsequent PR from `master` into `Development` should be made with the **merge** option (i.e., no squash).
  - [ ] **Immediately** delete the `hotfix` branch and create a new `hotfix` branch
  - [ ] increment the Symbiota version number in the symbase.php file and commit to the `hotfix` branch.
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2024-11-22 00:46 UTC, themerekat commented
I tried to upload this file using a Full Text Upload, but no otherCatalogNumbers are shown in the preview at all. What am I doing wrong?
![image](https://github.com/user-attachments/assets/b928f3dc-5b2e-405b-94c7-fae926521c70)

[Test_othercatnums.csv](https://github.com/user-attachments/files/17853710/Test_othercatnums.csv)

2024-11-22 00:50 UTC, themerekat commented
I think this solution doesn't handle when you're adding **only new** other catalog number values, rather than concatenating with what already exists. Maybe use CONCAT_WS, which automatically ignores NULL values?

2024-11-22 01:04 UTC, themerekat requested changes
See previous comments

2024-11-22 21:16 UTC, MuchQuak commented
> See previous comments

Nice catch, I didn't realize that `concat` would do by default. I add a much more rigid case so that the expected behavior occurs when either of the values is null.

2024-11-23 01:04 UTC, themerekat commented
Skeletal file uploader worked great!

But now I'm getting this error when I try to view the "records to be updated table" after attempting a Full Text File upload
![image](https://github.com/user-attachments/assets/794c893b-0aa2-430a-a0ad-d48de793a958)

The collection I was doing this upload in was a snapshot, so that might have been the problem?

Then I tested in another collection and it was correct:
![image](https://github.com/user-attachments/assets/432c8600-d020-4e3a-845a-b5b95a16b3ce)

2024-11-26 18:17 UTC, MuchQuak commented
> Skeletal file uploader worked great!
> 
> But now I'm getting this error when I try to view the "records to be updated table" after attempting a Full Text File upload ![image](https://private-user-images.githubusercontent.com/16688784/389147337-794c893b-0aa2-430a-a0ad-d48de793a958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDUxNzgsIm5iZiI6MTczMjY0NDg3OCwicGF0aCI6Ii8xNjY4ODc4NC8zODkxNDczMzctNzk0Yzg5M2ItMGFhMi00MzBhLWEwYWQtZDQ4ZGU3OTNhOTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE4MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYzNlMjdmMmQzMjVjMWRhZmYzNWMwOTY3NDQwNmYxZDljNGY0NGMyOTY5MjJmMzkzY2Y1M2M1NGQ1ZThkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._rED9qd6s6-s3S3Gaz41wH0sS1DsUGS6vTQYIEEMS0o)
> 
> The collection I was doing this upload in was a snapshot, so that might have been the problem? I'm also not sure if this is due to your changes or is a separate bug.
> 
> Then I tested in another collection and it was correct: ![image](https://private-user-images.githubusercontent.com/16688784/389147433-432c8600-d020-4e3a-845a-b5b95a16b3ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDUxNzgsIm5iZiI6MTczMjY0NDg3OCwicGF0aCI6Ii8xNjY4ODc4NC8zODkxNDc0MzMtNDMyYzg2MDAtZDAyMC00ZTNhLTg0NWEtYjViOTVhMTZiM2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE4MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljY2RmNGM1YWIyMTcwZjkxMGU3YzRiMDhkMWM5YmM5NDVkOWEwMjUwODIwMTgyMzM5YjIxYjQ1M2VkODdhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GAZ11-LYSMkUnjGFkwI3vjukUkramWzfb2IfKS7RBas)

How could I potentially replicate this issue? Is there a specific collection or upload I should use?

2024-11-26 18:33 UTC, themerekat commented
> > Skeletal file uploader worked great!
> > But now I'm getting this error when I try to view the "records to be updated table" after attempting a Full Text File upload ![image](https://private-user-images.githubusercontent.com/16688784/389147337-794c893b-0aa2-430a-a0ad-d48de793a958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDUxNzgsIm5iZiI6MTczMjY0NDg3OCwicGF0aCI6Ii8xNjY4ODc4NC8zODkxNDczMzctNzk0Yzg5M2ItMGFhMi00MzBhLWEwYWQtZDQ4ZGU3OTNhOTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE4MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYzNlMjdmMmQzMjVjMWRhZmYzNWMwOTY3NDQwNmYxZDljNGY0NGMyOTY5MjJmMzkzY2Y1M2M1NGQ1ZThkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._rED9qd6s6-s3S3Gaz41wH0sS1DsUGS6vTQYIEEMS0o)
> > The collection I was doing this upload in was a snapshot, so that might have been the problem? I'm also not sure if this is due to your changes or is a separate bug.
> > Then I tested in another collection and it was correct: ![image](https://private-user-images.githubusercontent.com/16688784/389147433-432c8600-d020-4e3a-845a-b5b95a16b3ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDUxNzgsIm5iZiI6MTczMjY0NDg3OCwicGF0aCI6Ii8xNjY4ODc4NC8zODkxNDc0MzMtNDMyYzg2MDAtZDAyMC00ZTNhLTg0NWEtYjViOTVhMTZiM2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE4MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljY2RmNGM1YWIyMTcwZjkxMGU3YzRiMDhkMWM5YmM5NDVkOWEwMjUwODIwMTgyMzM5YjIxYjQ1M2VkODdhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GAZ11-LYSMkUnjGFkwI3vjukUkramWzfb2IfKS7RBas)
> 
> How could I potentially replicate this issue? Is there a specific collection or upload I should use?

If you're using a copy of CCH2, you can use the BFRS collection. To make a test set, you can download a DwC archive and just keep the catalog number and verbatimElevation fields from the occurrences file. (Probably clear the existing values in verbatimElevation, minimumElevationInMeters, and maximumElevationInMeters for that collection, too.)

2024-12-03 16:24 UTC, themerekat commented
Doing a skeletal file upload and it seems to be working!

Can we add spaces between these delimiters?
![image](https://github.com/user-attachments/assets/42a8f719-1b41-40a6-9c2e-b788213b9965)

2024-12-04 20:16 UTC, MuchQuak commented
> Doing a skeletal file upload and it seems to be working!
> 
> Can we add spaces between these delimiters? For context, "This is: Another identifier" was an old value already in omoccuridentifiers, and "New Stuff: 654" is what is coming from the input file. ![image](https://private-user-images.githubusercontent.com/16688784/392049160-42a8f719-1b41-40a6-9c2e-b788213b9965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDMyNTIsIm5iZiI6MTczMzM0Mjk1MiwicGF0aCI6Ii8xNjY4ODc4NC8zOTIwNDkxNjAtNDJhOGY3MTktMWI0MS00MGE2LTljMmUtYjc4ODIxM2I5OTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIwMDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMmFlZjkwYzU4M2E2NDllMGRlMjQwYzIyYTgzZmVmZjE3ZTFmNjJhOTk5ZTZjZGZlMzcyMDU4YjMxYWNmODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2nU5HzJfym2fxHFC6u-rWRROX9_6s1HntEb-F7Fe-s8)

Okay changes were made

2024-12-04 21:12 UTC, themerekat approved these changes

2024-12-04 21:48 UTC, merged