add pull request checklist. It should automatically appear in the des…
Symbiota/Symbiota pull request #407
Opened 2023-03-13 19:14 UTC by Atticus29

…cription section any time a developer issues a pull request.

Because this represents a contract of sorts for conventions that we'll all be following, I'd like to get widespread (unanimous) approval for it.

2023-03-13 19:25 UTC, themerekat reviewed
Should line 8 say "(e.g., **by** a reformatter) ?

2023-03-13 19:28 UTC, themerekat reviewed
Also, regarding line 4, this hasn't happened in the past and means that all the text needs to be made into lang variables and a lang file created. Is this a 100% **must** requirement? Lang tags can always be added later.
I'm not advocating for one method (English-first vs. lang-tags always) or the other, but one potential argument for not requiring this is that someone basic like me could do the lang tags and thus free up other dev time.

2023-03-13 19:48 UTC, GregPost-ASU commented
Comments on line 3 of pull_request_template.md:
Feature branches should only be PRd into Development branch.  I believe bugfixes *should* be pulled into master, and also pulled into Developement.

2023-03-13 19:50 UTC, GregPost-ASU requested changes
modify line 3 so that bugfixes are pulled into both master and development..

2023-03-13 21:26 UTC, Atticus29 commented
> modify line 3 so that bugfixes are pulled into both master and development..

addressed the distinction between backlog bugs and hotfixes in commit 91a57625b.

2023-03-13 21:26 UTC, Atticus29 commented
> Comments on line 3 of pull_request_template.md: Feature branches should only be PRd into Development branch. I believe bugfixes _should_ be pulled into master, and also pulled into Developement.

addressed the distinction between backlog bugs and hotfixes in commit 91a57625b.

2023-03-13 21:26 UTC, Atticus29 commented
> Should line 8 say "(e.g., **by** a reformatter) ?

Good catch. Fixed in commit 91a57625b.

2023-03-13 21:30 UTC, Atticus29 commented
> Also, regarding line 4, this hasn't happened in the past and means that all the text needs to be made into lang variables and a lang file created. Is this a 100% **must** requirement? Lang tags can always be added later. I'm not advocating for one method (English-first vs. lang-tags always) or the other, but one potential argument for not requiring this is that someone basic like me could do the lang tags and thus free up other dev time.

I was thinking that for NEW code, it should be on the developers to do this. I think that there's no need to create more interruptive work for you when we're already in the code at the exact site of the issue. Clarified in commit 91a57625b.

I definitely DIDN'T mean that developers should make sure that the entire fire they're working in is internationalized; just the new stuff that they wrote. Legacy text that has not yet been internationalized should be in a ticket backlog IMHO.

Thoughts?

2023-03-13 21:36 UTC, themerekat commented
> > Also, regarding line 4, this hasn't happened in the past and means that all the text needs to be made into lang variables and a lang file created. Is this a 100% **must** requirement? Lang tags can always be added later. I'm not advocating for one method (English-first vs. lang-tags always) or the other, but one potential argument for not requiring this is that someone basic like me could do the lang tags and thus free up other dev time.
> 
> I was thinking that for NEW code, it should be on the developers to do this. I think that there's no need to create more interruptive work for you when we're already in the code at the exact site of the issue. Clarified in commit [91a5762](https://github.com/BioKIC/Symbiota/commit/91a57625ba9a9b6a74c909c4140c2d7392066673).
> 
> I definitely DIDN'T mean that developers should make sure that the entire fire they're working in is internationalized; just the new stuff that they wrote. Legacy text that has not yet been internationalized should be in a ticket backlog IMHO.
> 
> Thoughts?

Totally understand. It makes sense to not create more of a lang tag backlog. I was just wondering whether this (somewhat tedious) work might become a bottleneck to getting features out. Perhaps the bigger point is "I'm happy to do tedious code work if it frees up dev time, so feel free to assign me to do lang tag work for your PR if it's going to free up your time to do other stuff." Unless, of course, you'd like to do it yourself (it's kind of satisfying to have lower-brain-power tasks to do).

2023-03-13 21:44 UTC, GregPost-ASU commented
> > > Also, regarding line 4, this hasn't happened in the past and means that all the text needs to be made into lang variables and a lang file created. Is this a 100% **must** requirement? Lang tags can always be added later. I'm not advocating for one method (English-first vs. lang-tags always) or the other, but one potential argument for not requiring this is that someone basic like me could do the lang tags and thus free up other dev time.
> > 
> > 
> > I was thinking that for NEW code, it should be on the developers to do this. I think that there's no need to create more interruptive work for you when we're already in the code at the exact site of the issue. Clarified in commit [91a5762](https://github.com/BioKIC/Symbiota/commit/91a57625ba9a9b6a74c909c4140c2d7392066673).
> > I definitely DIDN'T mean that developers should make sure that the entire fire they're working in is internationalized; just the new stuff that they wrote. Legacy text that has not yet been internationalized should be in a ticket backlog IMHO.
> > Thoughts?
> 
> Totally understand. It makes sense to not create more of a lang tag backlog. I was just wondering whether this (somewhat tedious) work might become a bottleneck to getting features out. Perhaps the bigger point is "I'm happy to do tedious code work if it frees up dev time, so feel free to assign me to do lang tag work for your PR if it's going to free up your time to do other stuff." Unless, of course, you'd like to do it yourself (it's kind of satisfying to have lower-brain-power tasks to do).

Current code checks for the existence of the lang tag, and fails back to a hard coded english version.  This "fail-safe" method is useful for finding and debugging code.

2023-03-13 22:39 UTC, GregPost-ASU approved these changes

2023-03-14 17:51 UTC, themerekat approved these changes

2023-03-14 20:49 UTC, arbolitoloco approved these changes
Approved with minor modifications. I'm trying to keep the root clean by keeping only essential files there. Everything related to documentation should be added to the `docs` directory. This will not affect the PR template showing up.

2023-03-14 22:01 UTC, merged