Coll profile refactor mvp
Symbiota/Symbiota pull request #639
Opened 2023-09-27 20:35 UTC by Atticus29

# Pull Request Checklist:

# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferrably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages)
- [ ] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [ ] Comment which GitHub issue(s), if any does this PR address
- [ ] If this PR makes any changes that would require addional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2023-09-28 13:13 UTC, themerekat requested changes
I think users won't know what "search by identifier" means. They will likely think it means searching by the person who taxonomically identified the specimen. It would be more cumbersome, but I think users would respond better to "catalog number" or "catalog number / identifier".

2023-09-28 20:04 UTC, Atticus29 commented
> I think users won't know what "search by identifier" means. They will likely think it means searching by the person who taxonomically identified the specimen. It would be more cumbersome, but I think users would respond better to "catalog number" or "catalog number / identifier".

@themerekat good call. I wanted to emphasize that other identifiers in addition to catalog number would work in this search.
How about something like "Search by ID" and then as a `placeholder` in the input, "(e.g., catalog number)"?

2023-09-29 14:33 UTC, themerekat commented
> > I think users won't know what "search by identifier" means. They will likely think it means searching by the person who taxonomically identified the specimen. It would be more cumbersome, but I think users would respond better to "catalog number" or "catalog number / identifier".
> 
> @themerekat good call. I wanted to emphasize that other identifiers in addition to catalog number would work in this search. How about something like "Search by ID" and then as a `placeholder` in the input, "(e.g., catalog number)"?

As in, the "other identifiers" field? That makes sense and would be good to indicate somehow. Both "identifier" and "ID" have a different connotation in this domain, so I don't think we can easily use them. Catalog number is generally what people think of. I'm interested in what you mean by using a placeholder, though. Is that an alternate text or what you see when you hover over the field? (if we want to continue this via Slack / huddle, we can!)

2023-10-02 21:37 UTC, Atticus29 commented
Ok. Responded to all code review feedback.

2023-10-02 21:37 UTC, themerekat approved these changes

2023-10-02 21:38 UTC, merged