Openid auth
Symbiota/Symbiota pull request #753
Opened 2023-12-06 22:42 UTC by Atticus29

# Pull Request Checklist:

# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages)
- [ ] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [ ] Comment which GitHub issue(s), if any does this PR address
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2023-12-06 22:45 UTC, Atticus29 commented on config/schema/3.0/dev/third_party_auth_table.sql
> +CREATE TABLE `users_thirdpartyauth` (
Leaving this in dev directory until next release.

2023-12-07 00:13 UTC, themerekat requested changes
Wow, amazing work! Have not tested the workflow, but the aesthetics seem ok. One request: could the "Log in with OID" button be centered on the page?

2023-12-11 00:15 UTC, Atticus29 commented
> 4ef4b2c

@themerekat fixed in 4ef4b2c, and fixed the centering of the login page while I was at it for good measure.

The fixes at different screen sizes:


<img width="1552" alt="Screen Shot 2023-12-10 at 4 15 04 PM" src="https://github.com/BioKIC/Symbiota/assets/2775448/71aee740-1a69-40e0-8f96-b6f02fbf49cd">

<img width="1552" alt="Screen Shot 2023-12-10 at 4 14 58 PM" src="https://github.com/BioKIC/Symbiota/assets/2775448/a5b02dd0-4891-4e6c-bb18-6b09672afa66">

<img width="1552" alt="Screen Shot 2023-12-10 at 4 14 42 PM" src="https://github.com/BioKIC/Symbiota/assets/2775448/774ebfb1-165c-40fc-9627-c36fb7904e09">

2023-12-11 14:50 UTC, themerekat approved these changes

2023-12-11 14:50 UTC, themerekat commented
@Atticus29 , looks great, thank you!

2023-12-11 14:58 UTC, merged