Jquery update
Symbiota/Symbiota pull request #857
Opened 2024-01-12 22:11 UTC by NikitaSalikov

# Changes Made:

## Jquery Update:

- Switched all jquery to minified versions for better optimisation.

- Updated jquery.min.js to v 3.7.1, updated jquery-ui.min.js and jquery-ui.min.css to 1.13.2.

- Removed all older versions jquery files and folders including them.

- Fixed jquery-ui.min.css file to display original color design for tabs.

## CSS file issue:

I had to manually change the values for "ui-widget" and others to preserve original design. This could mean that some other pages' stylings are also impacted. I looked through the files and didn't find anything drastically different, but I could've overlooked.

One of the solutions could be to use the old css file.

# Pull Request Checklist:

# Pre-Approval

- [X] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [N/A] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [X] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [N/A] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [N/A] There are no linter errors
- [X] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [X] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [N/A] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [X] Comment which GitHub issue(s), if any does this PR address:
https://github.com/orgs/BioKIC/projects/6/views/14?filterQuery=nikita++status%3ATodo%2C%22In+Progress%22%2C%22Code+Review%22%2CBlocked%2C%22In+Test%22&pane=issue&itemId=49330427
- [N/A] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2024-01-15 18:11 UTC, NikitaSalikov commented on checklists/checklistadminchildren.php
Understood! I'll remove the htmlspecialchar in $CSS_BASE_PATH from all the pages where it exists.

2024-01-18 00:54 UTC, Atticus29 approved these changes
I found a squashed a bug on collections/search/index.php. I also removed another jquery file in collections/search that's no longer needed.

I did very light QAing and didn't find much else wrong. I'm sure we're missing something, but let's cross that bridge when we get there. I say we go ahead and merge.

2024-01-18 00:54 UTC, Atticus29 commented on checklists/checklistadminchildren.php
Thanks! Sorry to create extra work for us.

2024-01-18 00:54 UTC, Atticus29 commented on collections/editor/occurrenceeditor.php
> -	<script src="../../js/symb/collections.editor.autocomplete.js?ver=1" type="text/javascript"></script>
Not sure why this go deleted?

2024-01-18 03:35 UTC, Atticus29 requested changes
I saw this in qualys today that makes me hesitant to approve this after all:

![Screen Shot 2024-01-17 at 7 08 38 PM](https://github.com/BioKIC/Symbiota/assets/2775448/4cd2a3cb-2bd8-4935-8719-201ee0d261a4)

Please refer to the [Slack discussion here](https://symbiota-support.slack.com/archives/G01Q4PP6V3P/p1705547748764499) for more detail.

2024-02-16 21:11 UTC, Atticus29 approved these changes
Looks great. Spot check QA passes. Some merge conflicts looked a little gnarly, so I went ahead and resolved them for you. Ready for merge.

2024-02-19 17:19 UTC, merged