Language Tagged
Symbiota/Symbiota pull request #908
Opened 2024-02-05 06:03 UTC by RamisaZaman

# Pull Request Checklist:

# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [ ] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [ ] Comment which GitHub issue(s), if any does this PR address
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2024-02-05 07:15 UTC, Atticus29 commented
Hi, @RamisaZaman ! This generally looks great, but I'll leave it to @themerekat to review fully.

I am noticing, however, that the pull request checklist doesn't seem to be getting checked off, and I think that it should be. Let me know if you have any questions about that (perhaps Katie told you to disregard it for now or something). I think we're due for a meeting soon anyway!

2024-02-05 15:31 UTC, themerekat commented
> Hi, @RamisaZaman ! This generally looks great, but I'll leave it to @themerekat to review fully.
> 
> I am noticing, however, that the pull request checklist doesn't seem to be getting checked off, and I think that it should be. Let me know if you have any questions about that (perhaps Katie told you to disregard it for now or something). I think we're due for a meeting soon anyway!

@Atticus29 , good catch! I haven't walked through the PR checklist with Ramisa yet. Would you like to do that, or shall I at our next meeting?

2024-02-05 15:40 UTC, themerekat commented
@RamisaZaman , please rename PR with more detail (e.g., "Add language taggs to attributemining.php")

2024-02-05 15:50 UTC, themerekat requested changes

2024-02-05 15:50 UTC, themerekat commented on collections/traitattr/attributemining.php
> +		<title><?php echo $LANG['OCC_ATTRI_MINING_TOOL']?></title>
space after ]

2024-02-05 15:50 UTC, themerekat commented on collections/traitattr/attributemining.php
> +					alert("<?php echo $LANG['MUST_SELECT_TRAIT']?>");
space after ], here and throughout the file

2024-02-05 15:50 UTC, themerekat commented on content/lang/collections/traitattr/attributemining.en.php
> +$LANG['MUST_SELECT_FIELD_VALUE'] = 'You muct select at least one field value';
please fix typo: "You must select at least one field value"

2024-02-05 15:50 UTC, themerekat commented on content/lang/collections/traitattr/attributemining.en.php
> +$LANG['SELECT_COLLECT_TO_HARVEST'] = 'Select at last on collect to harvest from';
fix typo (from original file): "Select at least one collection to harvest from"

2024-02-05 15:50 UTC, themerekat commented on content/lang/collections/traitattr/attributemining.es.php
> +$LANG['SELECT_COLLECT_TO_HARVEST'] = 'Seleccione por fin la recolección para cosechar';
Replace with "Seleccione al menos una colección para cosechar"

2024-02-05 15:50 UTC, themerekat commented on content/lang/collections/traitattr/attributemining.fr.php
> +$LANG['SELECT_COLLECT_TO_HARVEST'] = 'Sélectionnez enfin lors de la collecte sur laquelle récolter';
Replace with "Sélectionner au moins une collection à partir de laquelle récolter"

2024-02-05 15:50 UTC, themerekat commented on collections/traitattr/attributemining.php
> +			if(is_numeric($collid)) echo '<a href="../misc/collprofiles.php?collid=' . htmlspecialchars($collid, HTML_SPECIAL_CHARS_FLAGS) . '&emode=1">'.$LANG['COLLECTION_MANAGEMENT'].'</a> &gt;&gt;';
Add spaces before and after periods

2024-02-05 15:50 UTC, themerekat commented on collections/traitattr/attributemining.php
> +			else if($IS_ADMIN || count($collRights) > 1) echo '<a href="attributemining.php">'.$LANG['ADJUST_COLLECTION_SELECTION'].'</a> &gt;&gt;';
See above

2024-02-05 15:50 UTC, themerekat commented on collections/traitattr/attributemining.php
> +					echo '<h2 class="heading">'.$LANG['SEARCH_ALL_COLLECTION'].'</h2>';
Spaces

2024-02-05 15:50 UTC, themerekat commented on collections/traitattr/attributemining.php
> +					echo '<legend style="font-weight:bold;font-size:130%"><a href="#" style="" onclick="toggleCollections()">'.$LANG['SEARCHING'].' '.count($collIdArr).' '.$LANG['COLLECTION'].'</a></legend>';
Spaces

2024-02-05 15:50 UTC, themerekat commented on collections/traitattr/attributemining.php
> +					echo '<div id="displayDiv" style="margin:0px 20px"><a href="#" onclick="toggleCollections()">'.$LANG['CLICK_DISPLAY_COLLEC_LIST'].'</a></div>';
Spaces

2024-02-05 15:50 UTC, themerekat commented on collections/traitattr/attributemining.php
> +										echo '<option value="0">'.$LANG['NO_ATTRI_AVAILABLE'].'</option>';
Spaces

2024-02-05 15:50 UTC, themerekat commented on content/lang/collections/traitattr/attributemining.en.php
> +$LANG['DWC_EXTENSION_FILE'] = ' DwC Extension file.';
I think you have too many spaces here, since there was a space in the HTML before this variable. Please check.

2024-02-06 20:32 UTC, themerekat approved these changes

2024-02-06 20:40 UTC, merged