Lang tag for collections/admin/igsnmapper.php
Symbiota/Symbiota pull request #943
Opened 2024-02-15 04:35 UTC by NikitaSalikov

# Changes made:

- Internationalized text

# Pull Request Checklist:

# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [ ] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [ ] Comment which GitHub issue(s), if any does this PR address:
https://github.com/orgs/BioKIC/projects/6/views/14?pane=issue&itemId=53327784
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2024-02-15 13:47 UTC, themerekat requested changes

2024-02-15 13:47 UTC, themerekat commented on collections/admin/igsnmapper.php
> +	<a href="../misc/collprofiles.php?collid=<?php echo htmlspecialchars($collid, HTML_SPECIAL_CHARS_FLAGS); ?>&emode=1"><?php echo $LANG['CALL_MANAGE'] ?></a> &gt;&gt;
Not super important, but I would change this to COLL_MANAGE

2024-02-15 13:47 UTC, themerekat commented on content/lang/collections/admin/igsnmapper.en.php
> +$LANG['CALL_MANAGE'] = 'Collection Management';
COLL_MANAGE

2024-02-15 13:47 UTC, themerekat commented on content/lang/collections/admin/igsnmapper.es.php
> +$LANG['CALL_MANAGE'] = 'Gestión de colecciones';
COLL_MANAGE

2024-02-15 13:47 UTC, themerekat commented on content/lang/collections/admin/igsnmapper.fr.php
> +$LANG['CALL_MANAGE'] = 'Gestion des collections';
COLL_MANAGE

2024-02-15 13:47 UTC, themerekat commented on collections/admin/igsnmapper.php
> +					<p><?php echo $LANG['REG_IGSN'] . " "?><a href="http://www.geosamples.org/interop" target="_blank">SESAR API Web Services</a></p>
Oops, missing a lang tag for SESAR API Web Services

2024-02-16 17:30 UTC, Atticus29 commented
@NikitaSalikov , is this one ready for re-review?

2024-02-16 17:31 UTC, NikitaSalikov commented
> @NikitaSalikov , is this one ready for re-review?

Yes, it is!

2024-02-16 17:37 UTC, themerekat approved these changes

2024-02-19 17:25 UTC, merged