508 Compliance for collections/georef/batchgeoreftool.php
Symbiota/Symbiota pull request #962
Opened 2024-02-22 23:59 UTC by RamisaZaman

# Pull Request Checklist:

# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [ ] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [ ] Comment which GitHub issue(s), if any does this PR address
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

2024-02-26 22:54 UTC, Atticus29 requested changes
The `<table>` in the form still needs to be replaced.

I'm also seeing the following issues still in TVP:

<img width="1552" alt="Screen Shot 2024-02-26 at 2 39 16 PM" src="https://github.com/BioKIC/Symbiota/assets/2775448/412cddd5-b0c0-4c99-9d08-2d3d606de273">

My recommendation would be to make the aria-labels unique. So, they get their own translations with slightly different wording.

2024-02-26 22:54 UTC, Atticus29 commented on collections/georef/batchgeoreftool.php
> +								<table class='xdebug-error xe-deprecated' dir='ltr' style='border: 1px solid black;'>
This whole table needs to be replaced with grid-like elements per [our discussion on slack the other day](https://symbiota-support.slack.com/archives/D06E4HD96JF/p1708730334701399?thread_ts=1708627799.608139&cid=D06E4HD96JF).

2024-02-26 22:54 UTC, Atticus29 commented on collections/georef/batchgeoreftool.php
> +								<table class='xdebug-error xe-deprecated' dir='ltr' style='border: 1px solid black;'>
Also, `xdebug-error` classes shouldn't be added in. Their presence (presumably in the Total Validator Pro [TVP from now on] pdf I sent you?) just means that the debugger found an issue and rendered a new table in the DOM. Kinda tricky. In this case, this table made by the debugger probably came from deprecation warnings with the `trim()` method that I fixed in [this commit](https://github.com/BioKIC/Symbiota/pull/962/commits/5a2892cfd6d259ef050d658394c9f9ccfa7cf4ee).

2024-02-27 05:51 UTC, RamisaZaman commented on collections/georef/batchgeoreftool.php
The table format has changed after replacing everything. Should I add the div like this: <div class="gridlike-form-cell">  ?

2024-02-27 05:52 UTC, RamisaZaman commented on collections/georef/batchgeoreftool.php
The table format has changed after replacing everything. Should I add the div like this:<div class="gridlike-form-cell">
?

2024-02-27 05:55 UTC, RamisaZaman commented on collections/georef/batchgeoreftool.php
The Table format has changed after replacing the td's with div's. Should I do it like this:         
div class="gridlike-form-cell"

2024-02-27 17:44 UTC, Atticus29 commented on collections/georef/batchgeoreftool.php
Hi, @RamisaZaman ! `class="gridlike-form-cell"` is not needed. It looks like you have resolved the table issues for the most part, although TVP doesn't seem to like the `colspan` attribute. Here's the latest TVP run results:

[tvp_batchgeoref.pdf](https://github.com/BioKIC/Symbiota/files/14423717/tvp_batchgeoref.pdf)

2024-03-05 02:58 UTC, Atticus29 requested changes
Hi, @RamisaZaman !

I went ahead and decided not to include a header on this page and instead just add a skip nav link manually. Check out how that was implemented [here](https://github.com/BioKIC/Symbiota/pull/962/commits/c204f379796ede4ca0835b7d2d6c7a2875428b96).

I'm noticing that if you use a keyboard to navigate the query form, the keyboard gets to the "Generate List" button before it gets to the Locality Term input. 

Can you look into how to reverse the order of those and implement the fix?

I think you might start to get somewhere with the `tabindex` attribute.

2024-03-11 19:48 UTC, RamisaZaman commented
> Hi, @RamisaZaman !
> 
> I went ahead and decided not to include a header on this page and instead just add a skip nav link manually. Check out how that was implemented [here](https://github.com/BioKIC/Symbiota/pull/962/commits/c204f379796ede4ca0835b7d2d6c7a2875428b96).
> 
> I'm noticing that if you use a keyboard to navigate the query form, the keyboard gets to the "Generate List" button before it gets to the Locality Term input.
> 
> Can you look into how to reverse the order of those and implement the fix?
> 
> I think you might start to get somewhere with the `tabindex` attribute.

2024-03-12 18:36 UTC, Atticus29 approved these changes
Changes look good, and the tab order makes sense now! Thanks!

2024-03-13 00:38 UTC, merged